name: "Build"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    name: Compile
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@latest

    - name: Get CMake
      uses: lukka/get-cmake@latest    
